#!/bin/bash
# copy this file to mpir root and run it

function build {
mkdir $SYSNAME && cd $SYSNAME && ../configure $1 && make -j $CPUS && make -j $CPUS check && cd .. && rm -rf $SYSNAME
if [ $? -ne 0 ] ; then echo "FAILED with options $1" ; exit 1 ; fi
}


touch demos/calc/*.c demos/calc/*.h

SYSNAME=$(uname -n)
if [ -e $SYSNAME ] ; then echo "ERROR directory $SYSNAME allready exist" ; exit 1 ; fi

CPUS=1
if [ -f /proc/cpuinfo ] ; then
	CPUS=$(cat /proc/cpuinfo  | grep -ce processor)
fi
if [ $SYSNAME == "mark" ] ; then
	CPUS=2
fi
if [ $SYSNAME == "mark2" ] ; then
	CPUS=2
fi
if [ $SYSNAME == "varro" ] ; then
	CPUS=2
fi
echo "Using $CPUS cpus"

FAT=0
SYS=$(./configfsf.guess | cut -f 1 -d -)
if [ $SYS == "x86_64" ] ; then FAT=1 ; fi
if [ $SYS == "x86" ] ; then FAT=1 ; fi

# standard build
build ""
# all features
build "--enable-cxx --enable-gmpcompat"
# all features and debug
exit
OPT="--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
# maximum debug
OPT="--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug --build=none"
if [ $FAT -eq 1 ] ; then
	# standard build
	OPT="--enable-fat"
	# all features
	OPT="--enable-fat --enable-cxx --enable-gmpcompat"
	# all features and debug
	OPT="--enable-fat --enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
fi


# try differnt gcc , build try 
