#!/bin/bash
# run this in the directory where everything will be built
# first param is mpir directory

DIR=$(pwd)
if [ $# -eq 1 ] ; then 
	# get absolute directory
	REL=$(echo $1 | head -c 1)
	if [ $REL == "/" ] ; then
	       DIR=$1
	else
	       DIR=$(pwd)/$1
	fi
fi

# dont want to run yacc
touch $DIR/demos/calc/*.c $DIR/demos/calc/*.h

SYSNAME=$(uname -n)
if [ -e $SYSNAME ] ; then echo "ERROR directory $SYSNAME allready exist" ; exit 1 ; fi

CPUS=1
if [ -f /proc/cpuinfo ] ; then
	CPUS=$(cat /proc/cpuinfo  | grep -ce processor)
fi
if [ $SYSNAME == "mark" ] ; then
	CPUS=2
fi
if [ $SYSNAME == "mark2" ] ; then
	CPUS=2
fi
if [ $SYSNAME == "varro" ] ; then
	CPUS=2
fi
echo "Using $CPUS cpus"

FAT=0
SYS=$($DIR/configfsf.guess | cut -f 1 -d -)
if [ $SYS == "x86_64" ] ; then FAT=1 ; fi
if [ $SYS == "x86" ] ; then FAT=1 ; fi

function build {
mkdir $SYSNAME && cd $SYSNAME && $DIR/configure $1 && make -j $CPUS && make -j $CPUS check && cd .. && rm -rf $SYSNAME
if [ $? -ne 0 ] ; then echo "FAILED with options $1" ; exit 1 ; fi
}


# standard build
build ""
# all features
build "--enable-cxx --enable-gmpcompat"
# all features and debug
build "--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
# maximum debug
build "--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug --build=none"
if [ $FAT -eq 1 ] ; then
	# standard build
	build "--enable-fat"
	# all features
	build "--enable-fat --enable-cxx --enable-gmpcompat"
	# all features and debug
	build "--enable-fat --enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
fi


# try differnt gcc , build try 
