#!/bin/bash
while true
do
./try -R -s 1-20 -r 1 mpn_add_n mpn_sub_n mpn_xor_n mpn_and_n mpn_ior_n mpn_nand_n mpn_nior_n mpn_xnor_n mpn_andn_n mpn_addmul_2 \
		mpn_iorn_n mpn_addadd_n mpn_addsub_n mpn_subadd_n mpn_sumdiff_n mpn_addmul_1 mpn_submul_1 mpn_mul_1 mpn_addlsh1_n \
		mpn_sublsh1_n mpn_com_n mpn_divexact_by3c mpn_divexact_byff mpn_divexact_by3 mpn_lshift mpn_rshift mpn_rsh1add_n \
		mpn_lshift1 mpn_rshift1 mpn_hamdist mpn_popcount MPN_COPY MPN_COPY_INCR MPN_COPY_DECR __GMPN_COPY mpn_rsh1sub_n \
		mpn_mul_2 mpn_divexact_byBm1of mpn_divrem_euclidean_qr_1 mpn_divrem_euclidean_r_1 mpn_lshift2 mpn_rshift2 \
		mpn_divrem_1 mpn_mod_1 mpn_sb_divrem_mn mpn_store MPN_ZERO
if [ $? -ne 0 ] ; then exit 1 ; fi
./try -R -s 1-50 -r 1 mpn_mul_basecase mpn_sqr_basecase mpn_redc_basecase mpn_tdiv_qr
if [ $? -ne 0 ] ; then exit 1 ; fi
#./try -R -s 10-300 -r 1 mpn_kara_mul_n mpn_kara_sqr_n
#if [ $? -ne 0 ] ; then exit 1 ; fi
#./try -R -s 50-1000 -r 1 mpn_toom3_mul_n mpn_toom3_sqr_n
#if [ $? -ne 0 ] ; then exit 1 ; fi
#./try -R -s 1-1000 -r 1 mpn_mul_n mpn_sqr_n mpn_mul
#if [ $? -ne 0 ] ; then exit 1 ; fi
done
